//Generated by 24HRS
package Controllers;

import Models.Appointment;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public class AppointmentController {

	Connector con = Connector.getInstance();

	private AppointmentController() {
	}

	private static final AppointmentController obj = new AppointmentController();

	public static AppointmentController getInstance() {
		return obj;
	}

	public void Save(Appointment data) throws Exception {
		con.getConnection();
		con.aud("INSERT INTO appointment(Name,date,time,doctor_name,email,contactNum,Hospital_Name) values ('"
				+ data.getName() + "','" + data.getDate() + "','" + data.getTime() + "','" + data.getDoctor_name()
				+ "','" + data.getEmail() + "','" + data.getContactNum() + "','" + data.getHospital_Name() + "') ");
	}

	public void Update(Appointment data) throws Exception {
		con.getConnection();
		con.aud("UPDATE appointment SET Name  = '" + data.getName() + "',date  = '" + data.getDate() + "',time  = '"
				+ data.getTime() + "',doctor_name  = '" + data.getDoctor_name() + "',email  = '" + data.getEmail()
				+ "',contactNum  = '" + data.getContactNum() + "',Hospital_Name  = '" + data.getHospital_Name()
				+ "' WHERE appointmentId = '" + data.getAppointmentId() + "'");
	}

	public void Delete(Appointment data) throws Exception {
		con.getConnection();
		con.aud("DELETE FROM appointment WHERE appointmentId = '" + data.getAppointmentId() + "'");
	}

	public List<Appointment> SearchAll() throws Exception {
		List<Appointment> objList = new ArrayList<Appointment>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM appointment");
		while (rset.next()) {
			Appointment obj = new Appointment();
			obj.setAppointmentId(rset.getInt(1));
			obj.setName(rset.getString(2));
			obj.setDate(rset.getString(3));
			obj.setTime(rset.getString(4));
			obj.setDoctor_name(rset.getString(5));
			obj.setEmail(rset.getString(6));
			obj.setContactNum(rset.getString(7));
			obj.setHospital_Name(rset.getString(8));
			objList.add(obj);
		}

		return objList;
	}

	public Appointment Search(int appointmentId) throws Exception {
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM appointment WHERE appointmentId = '" + appointmentId + "'");
		Appointment obj = new Appointment();
		if (rset.next()) {

			obj.setAppointmentId(rset.getInt(1));
			obj.setName(rset.getString(2));
			obj.setDate(rset.getString(3));
			obj.setTime(rset.getString(4));
			obj.setDoctor_name(rset.getString(5));
			obj.setEmail(rset.getString(6));
			obj.setContactNum(rset.getString(7));
			obj.setHospital_Name(rset.getString(8));
		}

		return obj;
	}

}