//Generated by 24HRS
package Controllers;

import Models.Doctor;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public class DoctorController {

	Connector con = Connector.getInstance();

	private DoctorController() {
	}

	private static final DoctorController obj = new DoctorController();

	public static DoctorController getInstance() {
		return obj;
	}

	public void Save(Doctor data) throws Exception {
		con.getConnection();
		con.aud("INSERT INTO doctor(Name,UserName,ContactNum,Email,Sex,Address,Password) values ('" + data.getName()
				+ "','" + data.getUserName() + "','" + data.getContactNum() + "','" + data.getEmail() + "','"
				+ data.getSex() + "','" + data.getAddress() + "','" + data.getPassword() + "') ");
	}

	public void Update(Doctor data) throws Exception {
		con.getConnection();
		con.aud("UPDATE doctor SET Name  = '" + data.getName() + "',UserName  = '" + data.getUserName()
				+ "',ContactNum  = '" + data.getContactNum() + "',Email  = '" + data.getEmail() + "',Sex  = '"
				+ data.getSex() + "',Address  = '" + data.getAddress() + "',Password  = '" + data.getPassword()
				+ "' WHERE doctorId = '" + data.getDoctorId() + "'");
	}

	public void Delete(Doctor data) throws Exception {
		con.getConnection();
		con.aud("DELETE FROM doctor WHERE doctorId = '" + data.getDoctorId() + "'");
	}

	public List<Doctor> SearchAll() throws Exception {
		List<Doctor> objList = new ArrayList<Doctor>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM doctor");
		while (rset.next()) {
			Doctor obj = new Doctor();
			obj.setDoctorId(rset.getInt(1));
			obj.setName(rset.getString(2));
			obj.setUserName(rset.getString(3));
			obj.setContactNum(rset.getString(4));
			obj.setEmail(rset.getString(5));
			obj.setSex(rset.getString(6));
			obj.setAddress(rset.getString(7));
			obj.setPassword(rset.getString(8));
			objList.add(obj);
		}

		return objList;
	}

	public Doctor Search(int doctorId) throws Exception {
		List<Doctor> objList = new ArrayList<Doctor>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM doctor WHERE doctorId='" + doctorId + "'");

		Doctor obj = new Doctor();
		if (rset.next()) {

			obj.setDoctorId(rset.getInt(1));
			obj.setName(rset.getString(2));
			obj.setUserName(rset.getString(3));
			obj.setContactNum(rset.getString(4));
			obj.setEmail(rset.getString(5));
			obj.setSex(rset.getString(6));
			obj.setAddress(rset.getString(7));
			obj.setPassword(rset.getString(8));
			objList.add(obj);

		}
		return obj;

	}

}