//Generated by 24HRS
package Models;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class Appointment{

	private int appointmentId;
	private String Name;
	private String date;
	private String time;
	private String doctor_name;
	private String email;
	private String contactNum;
	private String Hospital_Name;

public Appointment(){
}

public Appointment(int appointmentId){
	this.appointmentId = appointmentId;
}
public Appointment(int appointmentId,String Name,String date,String time,String doctor_name,String email,String contactNum,String Hospital_Name){
	this.appointmentId = appointmentId;
	this.Name = Name;
	this.date = date;
	this.time = time;
	this.doctor_name = doctor_name;
	this.email = email;
	this.contactNum = contactNum;
	this.Hospital_Name = Hospital_Name;
}

public int getAppointmentId(){
return appointmentId;
}

public void setAppointmentId(int appointmentId){
	this.appointmentId = appointmentId;
}

public String getName(){
return Name;
}

public void setName(String Name){
	this.Name = Name;
}

public String getDate(){
return date;
}

public void setDate(String date){
	this.date = date;
}

public String getTime(){
return time;
}

public void setTime(String time){
	this.time = time;
}

public String getDoctor_name(){
return doctor_name;
}

public void setDoctor_name(String doctor_name){
	this.doctor_name = doctor_name;
}

public String getEmail(){
return email;
}

public void setEmail(String email){
	this.email = email;
}

public String getContactNum(){
return contactNum;
}

public void setContactNum(String contactNum){
	this.contactNum = contactNum;
}

public String getHospital_Name(){
return Hospital_Name;
}

public void setHospital_Name(String Hospital_Name){
	this.Hospital_Name = Hospital_Name;
}

}