//Generated by 24HRS
package sliit.rest.api;


import Models.Doctor;
import Controllers.DoctorController;

import java.util.List;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("DoctorResources")
public class DoctorResource {

	@GET
	@Path("Doctors")
	@Produces({ MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON })
	public List<Doctor> getAllDoctors() throws Exception {
		return DoctorController.getInstance().SearchAll();
	}

	@GET
	@Path("Doctor/{doctorId}")
	@Produces({ MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON })
	public Doctor getDoctor(@PathParam("doctorId") int doctorId) throws Exception {
		return DoctorController.getInstance().Search(doctorId);
	}

	@POST
	@Path("Doctor")
	public String saveDoctor(Doctor obj) throws Exception {
		DoctorController.getInstance().Save(obj);
		return "Doctor Saved";
	}

	@PUT
	@Path("Doctor")
	public String updateDoctor(Doctor obj) throws Exception {
		DoctorController.getInstance().Update(obj);
		return "Doctor Updated";
	}

	@DELETE
	@Path("Doctor/{doctorId}")
	public String deleteDoctor(@PathParam("doctorId") int doctorId) throws Exception {
		Doctor obj = new Doctor();
		obj.setDoctorId(doctorId);
		DoctorController.getInstance().Delete(obj);
		return "Doctor Deleted";
	}
}